package expo.modules.ui

import android.graphics.Color
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.TextFieldColors
import androidx.compose.material3.TextFieldDefaults
import expo.modules.kotlin.records.Field
import expo.modules.kotlin.records.Record

data class TextInputColorsRecord(
  @Field val focusedTextColor: Color? = null,
  @Field val unfocusedTextColor: Color? = null,
  @Field val disabledTextColor: Color? = null,
  @Field val errorTextColor: Color? = null,
  @Field val focusedContainerColor: Color? = null,
  @Field val unfocusedContainerColor: Color? = null,
  @Field val disabledContainerColor: Color? = null,
  @Field val errorContainerColor: Color? = null,
  @Field val cursorColor: Color? = null,
  @Field val errorCursorColor: Color? = null,
  @Field val focusedIndicatorColor: Color? = null,
  @Field val unfocusedIndicatorColor: Color? = null,
  @Field val disabledIndicatorColor: Color? = null,
  @Field val errorIndicatorColor: Color? = null,
  @Field val focusedLeadingIconColor: Color? = null,
  @Field val unfocusedLeadingIconColor: Color? = null,
  @Field val disabledLeadingIconColor: Color? = null,
  @Field val errorLeadingIconColor: Color? = null,
  @Field val focusedTrailingIconColor: Color? = null,
  @Field val unfocusedTrailingIconColor: Color? = null,
  @Field val disabledTrailingIconColor: Color? = null,
  @Field val errorTrailingIconColor: Color? = null,
  @Field val focusedLabelColor: Color? = null,
  @Field val unfocusedLabelColor: Color? = null,
  @Field val disabledLabelColor: Color? = null,
  @Field val errorLabelColor: Color? = null,
  @Field val focusedPlaceholderColor: Color? = null,
  @Field val unfocusedPlaceholderColor: Color? = null,
  @Field val disabledPlaceholderColor: Color? = null,
  @Field val errorPlaceholderColor: Color? = null,
  @Field val focusedSupportingTextColor: Color? = null,
  @Field val unfocusedSupportingTextColor: Color? = null,
  @Field val disabledSupportingTextColor: Color? = null,
  @Field val errorSupportingTextColor: Color? = null,
  @Field val focusedPrefixColor: Color? = null,
  @Field val unfocusedPrefixColor: Color? = null,
  @Field val disabledPrefixColor: Color? = null,
  @Field val errorPrefixColor: Color? = null,
  @Field val focusedSuffixColor: Color? = null,
  @Field val unfocusedSuffixColor: Color? = null,
  @Field val disabledSuffixColor: Color? = null,
  @Field val errorSuffixColor: Color? = null
) : Record

fun TextInputColorsRecord.toTextFieldColors(): TextFieldColors {
  val d = TextFieldDefaults.colors()
  return TextFieldDefaults.colors(
    focusedTextColor = focusedTextColor.composeOrNull ?: d.focusedTextColor,
    unfocusedTextColor = unfocusedTextColor.composeOrNull ?: d.unfocusedTextColor,
    disabledTextColor = disabledTextColor.composeOrNull ?: d.disabledTextColor,
    errorTextColor = errorTextColor.composeOrNull ?: d.errorTextColor,
    focusedContainerColor = focusedContainerColor.composeOrNull ?: d.focusedContainerColor,
    unfocusedContainerColor = unfocusedContainerColor.composeOrNull ?: d.unfocusedContainerColor,
    disabledContainerColor = disabledContainerColor.composeOrNull ?: d.disabledContainerColor,
    errorContainerColor = errorContainerColor.composeOrNull ?: d.errorContainerColor,
    cursorColor = cursorColor.composeOrNull ?: d.cursorColor,
    errorCursorColor = errorCursorColor.composeOrNull ?: d.errorCursorColor,
    focusedIndicatorColor = focusedIndicatorColor.composeOrNull ?: d.focusedIndicatorColor,
    unfocusedIndicatorColor = unfocusedIndicatorColor.composeOrNull ?: d.unfocusedIndicatorColor,
    disabledIndicatorColor = disabledIndicatorColor.composeOrNull ?: d.disabledIndicatorColor,
    errorIndicatorColor = errorIndicatorColor.composeOrNull ?: d.errorIndicatorColor,
    focusedLeadingIconColor = focusedLeadingIconColor.composeOrNull ?: d.focusedLeadingIconColor,
    unfocusedLeadingIconColor = unfocusedLeadingIconColor.composeOrNull ?: d.unfocusedLeadingIconColor,
    disabledLeadingIconColor = disabledLeadingIconColor.composeOrNull ?: d.disabledLeadingIconColor,
    errorLeadingIconColor = errorLeadingIconColor.composeOrNull ?: d.errorLeadingIconColor,
    focusedTrailingIconColor = focusedTrailingIconColor.composeOrNull ?: d.focusedTrailingIconColor,
    unfocusedTrailingIconColor = unfocusedTrailingIconColor.composeOrNull ?: d.unfocusedTrailingIconColor,
    disabledTrailingIconColor = disabledTrailingIconColor.composeOrNull ?: d.disabledTrailingIconColor,
    errorTrailingIconColor = errorTrailingIconColor.composeOrNull ?: d.errorTrailingIconColor,
    focusedLabelColor = focusedLabelColor.composeOrNull ?: d.focusedLabelColor,
    unfocusedLabelColor = unfocusedLabelColor.composeOrNull ?: d.unfocusedLabelColor,
    disabledLabelColor = disabledLabelColor.composeOrNull ?: d.disabledLabelColor,
    errorLabelColor = errorLabelColor.composeOrNull ?: d.errorLabelColor,
    focusedPlaceholderColor = focusedPlaceholderColor.composeOrNull ?: d.focusedPlaceholderColor,
    unfocusedPlaceholderColor = unfocusedPlaceholderColor.composeOrNull ?: d.unfocusedPlaceholderColor,
    disabledPlaceholderColor = disabledPlaceholderColor.composeOrNull ?: d.disabledPlaceholderColor,
    errorPlaceholderColor = errorPlaceholderColor.composeOrNull ?: d.errorPlaceholderColor,
    focusedSupportingTextColor = focusedSupportingTextColor.composeOrNull ?: d.focusedSupportingTextColor,
    unfocusedSupportingTextColor = unfocusedSupportingTextColor.composeOrNull ?: d.unfocusedSupportingTextColor,
    disabledSupportingTextColor = disabledSupportingTextColor.composeOrNull ?: d.disabledSupportingTextColor,
    errorSupportingTextColor = errorSupportingTextColor.composeOrNull ?: d.errorSupportingTextColor,
    focusedPrefixColor = focusedPrefixColor.composeOrNull ?: d.focusedPrefixColor,
    unfocusedPrefixColor = unfocusedPrefixColor.composeOrNull ?: d.unfocusedPrefixColor,
    disabledPrefixColor = disabledPrefixColor.composeOrNull ?: d.disabledPrefixColor,
    errorPrefixColor = errorPrefixColor.composeOrNull ?: d.errorPrefixColor,
    focusedSuffixColor = focusedSuffixColor.composeOrNull ?: d.focusedSuffixColor,
    unfocusedSuffixColor = unfocusedSuffixColor.composeOrNull ?: d.unfocusedSuffixColor,
    disabledSuffixColor = disabledSuffixColor.composeOrNull ?: d.disabledSuffixColor,
    errorSuffixColor = errorSuffixColor.composeOrNull ?: d.errorSuffixColor
  )
}

fun TextInputColorsRecord.toOutlinedTextFieldColors(): TextFieldColors {
  val d = OutlinedTextFieldDefaults.colors()
  return OutlinedTextFieldDefaults.colors(
    focusedTextColor = focusedTextColor.composeOrNull ?: d.focusedTextColor,
    unfocusedTextColor = unfocusedTextColor.composeOrNull ?: d.unfocusedTextColor,
    disabledTextColor = disabledTextColor.composeOrNull ?: d.disabledTextColor,
    errorTextColor = errorTextColor.composeOrNull ?: d.errorTextColor,
    focusedContainerColor = focusedContainerColor.composeOrNull ?: d.focusedContainerColor,
    unfocusedContainerColor = unfocusedContainerColor.composeOrNull ?: d.unfocusedContainerColor,
    disabledContainerColor = disabledContainerColor.composeOrNull ?: d.disabledContainerColor,
    errorContainerColor = errorContainerColor.composeOrNull ?: d.errorContainerColor,
    cursorColor = cursorColor.composeOrNull ?: d.cursorColor,
    errorCursorColor = errorCursorColor.composeOrNull ?: d.errorCursorColor,
    focusedBorderColor = focusedIndicatorColor.composeOrNull ?: d.focusedIndicatorColor,
    unfocusedBorderColor = unfocusedIndicatorColor.composeOrNull ?: d.unfocusedIndicatorColor,
    disabledBorderColor = disabledIndicatorColor.composeOrNull ?: d.disabledIndicatorColor,
    errorBorderColor = errorIndicatorColor.composeOrNull ?: d.errorIndicatorColor,
    focusedLeadingIconColor = focusedLeadingIconColor.composeOrNull ?: d.focusedLeadingIconColor,
    unfocusedLeadingIconColor = unfocusedLeadingIconColor.composeOrNull ?: d.unfocusedLeadingIconColor,
    disabledLeadingIconColor = disabledLeadingIconColor.composeOrNull ?: d.disabledLeadingIconColor,
    errorLeadingIconColor = errorLeadingIconColor.composeOrNull ?: d.errorLeadingIconColor,
    focusedTrailingIconColor = focusedTrailingIconColor.composeOrNull ?: d.focusedTrailingIconColor,
    unfocusedTrailingIconColor = unfocusedTrailingIconColor.composeOrNull ?: d.unfocusedTrailingIconColor,
    disabledTrailingIconColor = disabledTrailingIconColor.composeOrNull ?: d.disabledTrailingIconColor,
    errorTrailingIconColor = errorTrailingIconColor.composeOrNull ?: d.errorTrailingIconColor,
    focusedLabelColor = focusedLabelColor.composeOrNull ?: d.focusedLabelColor,
    unfocusedLabelColor = unfocusedLabelColor.composeOrNull ?: d.unfocusedLabelColor,
    disabledLabelColor = disabledLabelColor.composeOrNull ?: d.disabledLabelColor,
    errorLabelColor = errorLabelColor.composeOrNull ?: d.errorLabelColor,
    focusedPlaceholderColor = focusedPlaceholderColor.composeOrNull ?: d.focusedPlaceholderColor,
    unfocusedPlaceholderColor = unfocusedPlaceholderColor.composeOrNull ?: d.unfocusedPlaceholderColor,
    disabledPlaceholderColor = disabledPlaceholderColor.composeOrNull ?: d.disabledPlaceholderColor,
    errorPlaceholderColor = errorPlaceholderColor.composeOrNull ?: d.errorPlaceholderColor,
    focusedSupportingTextColor = focusedSupportingTextColor.composeOrNull ?: d.focusedSupportingTextColor,
    unfocusedSupportingTextColor = unfocusedSupportingTextColor.composeOrNull ?: d.unfocusedSupportingTextColor,
    disabledSupportingTextColor = disabledSupportingTextColor.composeOrNull ?: d.disabledSupportingTextColor,
    errorSupportingTextColor = errorSupportingTextColor.composeOrNull ?: d.errorSupportingTextColor,
    focusedPrefixColor = focusedPrefixColor.composeOrNull ?: d.focusedPrefixColor,
    unfocusedPrefixColor = unfocusedPrefixColor.composeOrNull ?: d.unfocusedPrefixColor,
    disabledPrefixColor = disabledPrefixColor.composeOrNull ?: d.disabledPrefixColor,
    errorPrefixColor = errorPrefixColor.composeOrNull ?: d.errorPrefixColor,
    focusedSuffixColor = focusedSuffixColor.composeOrNull ?: d.focusedSuffixColor,
    unfocusedSuffixColor = unfocusedSuffixColor.composeOrNull ?: d.unfocusedSuffixColor,
    disabledSuffixColor = disabledSuffixColor.composeOrNull ?: d.disabledSuffixColor,
    errorSuffixColor = errorSuffixColor.composeOrNull ?: d.errorSuffixColor
  )
}
